# TODO: Replace gitpod with master
image: ghcr.io/conda/conda-ci:gitpod-linux-python3.9
tasks:
  - name: initialize
    init: |
      conda install --file requirements.txt
      cd notebooks
    command: for f in *.ipynb; do jupyter nbconvert --execute --to notebook --inplace "$f"; done
vscode:
  extensions:
    - eamodio.gitlens
    - ms-python.python
    - ms-python.vscode-pylance
